project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "R-shiny workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Inhoud workshop"
        menu:
          - text: Voorbereiding voor de Workshop
            href: presentaties/voorbereiding.qmd
          - text: Basis R
            href: presentaties/basis.qmd
          - text: Data in R
            href: presentaties/dataanalyse.qmd
          - text: Grafieken in R
            href: presentaties/grafieken.qmd
          - text: Werken met Shiny
            href: presentaties/shiny.qmd
            
      - text: "Werkende Apps"
        menu:
          - text: "App melkproductie"
            href: https://dashboard.costeranalytics.nl/wsappproductie/
          - text: "App plantengroei"
            href: https://dashboard.costeranalytics.nl/wsappproductie/

